Getting the latest updates from toru173...

diff --git a/install b/install
--- a/install
+++ b/install
@@ -190,7 +190,7 @@ IF ERRORLEVEL 1 (
 
 :: Here we download the latest release from GitHub to INSTALL_FOLDER
 ECHO Downloading the latest version from GitHub...
-curl -L https://github.com/myakirimiya/nomi-discord-python/releases/latest/download/install.zip -o "%DOWNLOAD_DIR%\install.zip" --progress-bar --remove-on-error
+curl -L https://github.com/myakirimiya/nomi-discord-python/releases/latest/download/install.zip -o "%DOWNLOAD_DIR%\install.zip" --progress-bar
 IF NOT EXIST "%DOWNLOAD_DIR%\install.zip" (
     ECHO Something went wrong during the download. Please try again.
     GOTO CLEANUP
@@ -198,7 +198,7 @@ IF NOT EXIST "%DOWNLOAD_DIR%\install.zip" (
 
 :: Warn the user that existing files will be overwritten. No going back now!
 ECHO:
-ECHO WARNING: This step will overwrite existing installation files in the directory:
+ECHO WARNING: This step will overwrite the existing installation in the directory:
 ECHO %INSTALL_DIR%
 ECHO:
 ECHO Any configuration files or startup scripts should be safe; however, if
@@ -334,7 +334,7 @@ trap "cleanup" EXIT INT
 # Cleanup function
 function cleanup() {
     EXIT_CODE=$?
-    if [[ -n "$INSTALL_DIR" ]] && [[ -f "$INSTALL_DIR/.downloads/install.zip" ]]; then
+    if [[ -n "$INSTALL_DIR" ]] && [[ -d "$INSTALL_DIR/.downloads" ]]; then
         rm -rf "$INSTALL_DIR/.downloads/"
     fi
     exit $EXIT_CODE
@@ -361,6 +361,13 @@ function check_dependancies() {
         TAR_INSTALLED=0
     fi
 
+    # Check if unzip is installed
+    if command -v unzip  > /dev/null 2>&1; then
+        UNZIP_INSTALLED=1
+    else
+        UNZIP_INSTALLED=0
+    fi
+
     # Display installation statuses
     if [[ "$DOCKER_INSTALLED" -eq 1 ]]; then
         echo "[x] Docker is installed"
@@ -374,8 +381,15 @@ function check_dependancies() {
         echo "[ ] tar is not installed"
     fi
 
+    if [[ "$UNZIP_INSTALLED" -eq 1 ]]; then
+        echo "[x] unzip is installed"
+    else
+        echo "[ ] unzip is not installed"
+    fi
+
+
     # If both are installed, continue
-    if [[ "$DOCKER_INSTALLED" -eq 1 ]] && [[ "$TAR_INSTALLED" -eq 1 ]]; then
+    if [[ "$DOCKER_INSTALLED" -eq 1 ]] && [[ "$TAR_INSTALLED" -eq 1 || "$UNZIP_INSTALLED" -eq 1 ]]; then
         echo
         echo "All required software is installed."
     else
@@ -420,15 +434,41 @@ function check_dependancies() {
                 elif command -v zypper  > /dev/null 2>&1; then
                     echo "For SUSE or openSUSE systems, you can install tar by running:"
                     echo "    sudo zypper install tar"
-                elif command -v brew  > /dev/null 2>&1; then
-                    echo "For macOS users, you can install GNU tar by running:"
-                    echo "    brew install gnu-tar"
                 else
                     echo "Your system does not have a recognized package manager."
                     echo "Please refer to your system documentation on how to install tar."
                 fi
             fi
+
+            # Check if unzip is installed. Prompt the user to download it if not
+            # by attempting to guess what package manager they are using (if any)
+            if [[ "$UNZIP_INSTALLED" -eq 0 ]]; then
+                echo
+                echo "unzip is required but not installed."
+                echo "You may need to install it using a package manager."
+                echo
+
+                # Provide examples of how to install unzip depending on the system
+                if command -v apt  > /dev/null 2>&1; then
+                    echo "For Ubuntu or Debian-based systems, you can install unzip by running:"
+                    echo "    sudo apt update && sudo apt install unzip"
+                elif command -v yum  > /dev/null 2>&1; then
+                    echo "For Red Hat, CentOS, or Fedora systems, you can install unzip by running:"
+                    echo "    sudo yum install unzip"
+                elif command -v dnf  > /dev/null 2>&1; then
+                    echo "For newer Fedora systems (or RHEL 8+), you can install unzip by running:"
+                    echo "    sudo dnf install unzip"
+                elif command -v zypper  > /dev/null 2>&1; then
+                    echo "For SUSE or openSUSE systems, you can install unzip by running:"
+                    echo "    sudo zypper install unzip"
+                else
+                    echo "Your system does not have a recognized package manager."
+                    echo "Please refer to your system documentation on how to install unzip."
+                fi
+            fi
+
         fi
+        echo
         echo "Some required software is missing. Please install the missing software"
         echo "and re-run the installer."
         exit 1
@@ -524,7 +564,7 @@ WRITE_TEST="${INSTALL_DIR}/.downloads"
 
 # Check we have write access to the location the user has provided.
 # We'll try to create a test directory to check write access.
-if ! mkdir "$WRITE_TEST" 2>/dev/null; then
+if ! mkdir -p "$WRITE_TEST" 2>/dev/null; then
     echo "It looks like we can't write to the folder: $INSTALL_DIR"
     echo "Please make sure you have permission to write to this directory and try again."
     exit 1
@@ -532,7 +572,7 @@ fi
 
 # Download the latest release from GitHub to INSTALL_FOLDER
 echo "Downloading the latest version from GitHub..."
-curl -L https://github.com/myakirimiya/nomi-discord-python/releases/latest/download/install.zip -o "$INSTALL_DIR/.downloads/install.zip" --progress-bar --remove-on-error
+curl -L https://github.com/myakirimiya/nomi-discord-python/releases/latest/download/install.zip -o "$INSTALL_DIR/.downloads/install.zip" --progress-bar
 
 # Check if the download was successful
 if [[ ! -f "$INSTALL_DIR/.downloads/install.zip" ]]; then
@@ -542,7 +582,7 @@ fi
 
 # Warn the user that existing files will be overwritten. No going back now!
 echo
-echo "WARNING: This step will overwrite existing installation files in the directory:"
+echo "WARNING: This step will overwrite the existing installation in the directory:"
 echo "$INSTALL_DIR"
 echo
 echo "Any configuration files or startup scripts should be safe; however, if"
@@ -562,12 +602,14 @@ fi
 # into that before before we can filter by the things we want to download.
 # After that, get the install script, the license and everything inside
 # the 'app' subdirectory. GNU tar and bsdtar behave differently so we need
-# to accomodate that
+# to accomodate for that
 echo "Extracting installation files..."
-if tar --version 2>&1 | grep -q "GNU tar"; then
-    tar -xvf "$INSTALL_DIR/.downloads/install.zip" -C "$INSTALL_DIR" \
-        --wildcards --no-anchored "install" "LICENSE" "app/*" "setup/*" "update/*"
+if tar --version 2>&1 | grep -qi "gnu tar"; then
+    # If we have GNU tar, we need to use unzip instead.
+    unzip "$INSTALL_DIR/.downloads/install.zip" -d "$INSTALL_DIR" \
+        "install" "LICENSE" "app/*" "setup/*" "update/*"
 elif tar --version 2>&1 | grep -qi "bsdtar"; then
+    # bsdtar can do what we need
     tar -xvf "$INSTALL_DIR/.downloads/install.zip" -C "$INSTALL_DIR" \
         --include="install" --include="LICENSE" --include="app/*" --include="setup/*" --include="update/*"
 else
